
###Test
POST http://localhost:3033/v1/api/shop/signup
Content-Type: application/json

{
  "name": "Thuong",
  "email": "a3631117@gmail.com",
  "password": "avc123"
}

### SignUP
POST http://localhost:3033/v1/api/auth/signup
Content-Type: application/json
x-api-key: b5e5b485ccf2f42371664e28df25fc565ccb0f0c6fae7370ed5c98e14748b9f6b142bcd9e7bde12ec91e43f8c804ac8534543c1304cfdcc9f4bb1cb83d5e8dbe

{
  "name": "Thuong",
  "email": "a3631122@gmail.com",
  "password": "avc123"
}

### Login
POST http://localhost:3033/v1/api/auth/login
Content-Type: application/json
x-api-key: b5e5b485ccf2f42371664e28df25fc565ccb0f0c6fae7370ed5c98e14748b9f6b142bcd9e7bde12ec91e43f8c804ac8534543c1304cfdcc9f4bb1cb83d5e8dbe

{
  "email": "a3631122@gmail.com",
  "password": "avc123"
}
### Logout
POST http://localhost:3033/v1/api/auth/logout
Content-Type: application/json
x-api-key:b5e5b485ccf2f42371664e28df25fc565ccb0f0c6fae7370ed5c98e14748b9f6b142bcd9e7bde12ec91e43f8c804ac8534543c1304cfdcc9f4bb1cb83d5e8dbe
x-client-id:6421d51e8fbf2fdc5203be01
authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDIxZDUxZThmYmYyZmRjNTIwM2JlMDEiLCJlbWFpbCI6ImEzNjMxMTIyQGdtYWlsLmNvbSIsImlhdCI6MTY4MDAwOTM0NiwiZXhwIjoxNjgwMTgyMTQ2fQ.jRgSt6mGkkWaMWIDNRd9eFQmp-prNQ-8U7oe4KoxOBA

### Refresh Token
POST http://localhost:3033/v1/api/auth/refresh-token
Content-Type: application/json
x-api-key:b5e5b485ccf2f42371664e28df25fc565ccb0f0c6fae7370ed5c98e14748b9f6b142bcd9e7bde12ec91e43f8c804ac8534543c1304cfdcc9f4bb1cb83d5e8dbe
x-client-id:6421d51e8fbf2fdc5203be01
x-token-id:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDIxZDUxZThmYmYyZmRjNTIwM2JlMDEiLCJlbWFpbCI6ImEzNjMxMTIyQGdtYWlsLmNvbSIsImlhdCI6MTY4MDAwOTQ4NiwiZXhwIjoxNjgwNjE0Mjg2fQ.4F7yYu7PlhAdDM71OXJj_N1c6aP-7tq21b4wxfE1O_w